# SITE CONFIGURATION
title: Casualidade # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://casualidade.tk/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Pedro Sader Azevedo
  links:
    - https://www.facebook.com/pedro.azevedo.52831666
    - https://www.linkedin.com/in/pedro-sader-azevedo-a40303194/
    - https://github.com/PeSader

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Propósito', link: '/proposito'}
  - {name: 'Autor', link: '/autor'}

tagline: >
  Considerações de um amante das Humanas, casado com as Exatas

hero_img: posts/books.jpeg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: casualidadeblog@gmail.com # email for form submission

#twitter_username: None # replace with your_twitter_username or comment to remove link from footer
#github_username:  PeSader # replace with your_github_username or comment to remove link from footer
#instagram_username: pe.sader # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
#theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
